version: 2.1
workflows:
  version: 2.1
  publish-to-npm:
    jobs:
      - publish:
          context: bavard
          filters:
            branches:
              only: main
jobs:
  publish:
    docker:
      - image: "circleci/node:latest"
    steps:
      - checkout
      - run:
          name: install
          command: npm install
      - run:
          name: publish
          command: |
            echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
            npm publish
